# Define an array of symbolic link sources and targets
$(pwd)/zsh/.zshrc:$HOME/.zshrc
$(pwd)/vim/.vimrc:$HOME/.vimrc
$(pwd)/mise/config.toml:$HOME/.config/mise/config.toml
$(pwd)/starship/starship.toml:$HOME/.config/starship.toml
$(pwd)/vscode/settings.json:$HOME/.config/Code/User/settings.json