# ----------------------------------
# TOOLS (globais)
# ----------------------------------
[tools]
go = "1.26"
gh = "latest"
helm = "latest"
shfmt = "latest"
aws-cli = "latest"
kubectl = "latest"
talosctl = "latest"
helmfile = "latest"
terraform = "latest"
shellcheck = "latest"
terragrunt = "latest"
pre-commit = "latest"
"aqua:helm/helm" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:go-task/task" = "latest"
"aqua:getsops/sops" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:cilium/cilium-cli" = "latest"
"aqua:helmfile/helmfile" = "latest"
"aqua:budimanjojo/talhelper" = "latest"

# ----------------------------------
# ENV GLOBAL
# ----------------------------------
[env]
EDITOR = "vim"

# ----------------------------------
# SETTINGS
# ----------------------------------
[settings]
idiomatic_version_file_enable_tools = ["node"]
